import type { Operator } from '@engine/types';

/**
 * DEFENSE operators. See the IP note in `operators.attack.ts` — the same rule
 * applies here: names and gadget strings live only in this layer.
 */
export const defenseOperators: Operator[] = [
  {
    id: 'def_bandit',
    name: 'Bandit',
    unit: 'GSG 9',
    side: 'DEF',
    speed: 3,
    roles: ['anti-breach', 'roam'],
    stats: { aim: 84, utility: 84, entry: 76, clutch: 82 },
    gadget: { name: 'Fiação Improvisada', tags: ['anti-breach'], counters: ['hard-breach'], power: 0.82 },
    rarity: 'elite',
    draftWeight: 0.95,
  },
  {
    id: 'def_kaid',
    name: 'Kaid',
    unit: 'GIGR',
    side: 'DEF',
    speed: 1,
    roles: ['anti-breach', 'anchor'],
    stats: { aim: 79, utility: 86, entry: 66, clutch: 80 },
    gadget: { name: 'Electroclaw', tags: ['anti-breach'], counters: ['hard-breach'], power: 0.85 },
    rarity: 'elite',
    draftWeight: 0.95,
  },
  {
    id: 'def_mute',
    name: 'Mute',
    unit: 'SAS',
    side: 'DEF',
    speed: 2,
    roles: ['intel-denial', 'anti-breach', 'anchor'],
    stats: { aim: 76, utility: 88, entry: 64, clutch: 74 },
    gadget: {
      name: 'Perturbador de Sinal',
      tags: ['intel-denial', 'anti-breach'],
      counters: ['intel', 'hard-breach'],
      power: 0.8,
    },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'def_vigil',
    name: 'Vigil',
    unit: '707th SMB',
    side: 'DEF',
    speed: 3,
    roles: ['intel-denial', 'roam'],
    stats: { aim: 83, utility: 78, entry: 78, clutch: 84 },
    gadget: { name: 'Manto ERC-7', tags: ['intel-denial'], counters: ['intel'], power: 0.74 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'def_kapkan',
    name: 'Kapkan',
    unit: 'Spetsnaz',
    side: 'DEF',
    speed: 2,
    roles: ['trap', 'anchor'],
    stats: { aim: 80, utility: 80, entry: 70, clutch: 78 },
    gadget: { name: 'Dispositivo de Entrada', tags: ['trap'], counters: ['entry'], power: 0.55 },
    rarity: 'common',
    draftWeight: 1.05,
  },
  {
    id: 'def_frost',
    name: 'Frost',
    unit: 'JTF2',
    side: 'DEF',
    speed: 2,
    roles: ['trap', 'anchor'],
    stats: { aim: 78, utility: 82, entry: 68, clutch: 80 },
    gadget: { name: 'Armadilha de Boas-Vindas', tags: ['trap'], counters: ['entry'], power: 0.7 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'def_lesion',
    name: 'Lesion',
    unit: 'SDU',
    side: 'DEF',
    speed: 2,
    roles: ['trap', 'intel'],
    stats: { aim: 81, utility: 84, entry: 72, clutch: 80 },
    gadget: { name: 'Minas Gu', tags: ['trap', 'intel'], counters: ['entry'], power: 0.12 },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'def_valkyrie',
    name: 'Valkyrie',
    unit: 'Navy SEALs',
    side: 'DEF',
    speed: 2,
    roles: ['intel', 'roam'],
    stats: { aim: 84, utility: 84, entry: 76, clutch: 86 },
    gadget: { name: 'Olho Negro', tags: ['intel'], counters: [], power: 0.8 },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'def_maestro',
    name: 'Maestro',
    unit: 'GIS',
    side: 'DEF',
    speed: 1,
    roles: ['intel', 'anchor'],
    stats: { aim: 79, utility: 86, entry: 64, clutch: 82 },
    gadget: { name: 'Câmera Evil Eye', tags: ['intel'], counters: [], power: 0.78 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'def_jager',
    name: 'Jäger',
    unit: 'GSG 9',
    side: 'DEF',
    speed: 3,
    roles: ['anti-gadget', 'roam'],
    stats: { aim: 87, utility: 76, entry: 80, clutch: 84 },
    gadget: { name: 'ADS Magpie', tags: ['anti-gadget'], counters: ['flash'], power: 0.76 },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'def_doc',
    name: 'Doc',
    unit: 'GIGN',
    side: 'DEF',
    speed: 1,
    roles: ['heal', 'anchor'],
    stats: { aim: 78, utility: 82, entry: 62, clutch: 80 },
    gadget: { name: 'Pistola Stim', tags: ['heal'], counters: [], power: 0.8 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'def_rook',
    name: 'Rook',
    unit: 'GIGN',
    side: 'DEF',
    speed: 1,
    roles: ['anchor', 'heal'],
    stats: { aim: 77, utility: 80, entry: 62, clutch: 78 },
    gadget: { name: 'Placas de Armadura', tags: ['heal'], counters: [], power: 0.7 },
    rarity: 'common',
    draftWeight: 1.1,
  },
];
