import type { Operator } from '@engine/types';

/**
 * IP-FREE OPERATOR PACK.
 *
 * Rainbow Six Siege operator names, units and gadget names are Ubisoft
 * trademarks. This pack carries identical stats, tags, gadget behaviour and
 * draft weights under original names, so balance work holds across both packs
 * and the game plays exactly the same.
 *
 * Selected with `VITE_CONTENT_PACK=generic`.
 *
 * This file is deliberately STANDALONE rather than deriving from
 * `operators.attack.ts`. Deriving would import the licensed names, which then
 * ship in the bundle even though nothing renders them — defeating the entire
 * purpose of having the pack.
 *
 * Regenerate with: npx tsx scripts/gen-generic-pack.ts
 */
export const genericAttackOperators: Operator[] = [
  {
    id: 'atk_gen_0',
    name: 'Forja',
    unit: 'Brigada Ígnea',
    side: 'ATK',
    speed: 2,
    roles: ['hard-breach', 'support'],
    stats: { aim: 78, utility: 88, entry: 70, clutch: 72 },
    gadget: {
      name: 'Carga Térmica',
      tags: ['hard-breach'],
      counters: ['anti-breach'],
      power: 0.8,
    },
    rarity: 'elite',
    draftWeight: 1,
  },
  {
    id: 'atk_gen_1',
    name: 'Cinza',
    unit: 'Divisão Aurora',
    side: 'ATK',
    speed: 3,
    roles: ['hard-breach', 'entry'],
    stats: { aim: 82, utility: 84, entry: 78, clutch: 74 },
    gadget: {
      name: 'Lança-Pinos',
      tags: ['hard-breach'],
      counters: ['anti-breach'],
      power: 0.75,
    },
    rarity: 'elite',
    draftWeight: 1,
  },
  {
    id: 'atk_gen_2',
    name: 'Surto',
    unit: 'Guarda Real',
    side: 'ATK',
    speed: 2,
    roles: ['anti-gadget', 'support'],
    stats: { aim: 76, utility: 90, entry: 66, clutch: 70 },
    gadget: {
      name: 'Pulso Eletromagnético',
      tags: ['anti-gadget'],
      counters: ['anti-breach', 'trap'],
      power: 0.85,
    },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'atk_gen_3',
    name: 'Radar',
    unit: 'Vanguarda Norte',
    side: 'ATK',
    speed: 3,
    roles: ['anti-gadget', 'intel'],
    stats: { aim: 80, utility: 82, entry: 74, clutch: 76 },
    gadget: {
      name: 'Scanner de Campo',
      tags: ['anti-gadget', 'intel'],
      counters: ['trap'],
      power: 0.7,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'atk_gen_4',
    name: 'Estopim',
    unit: 'Brigada Ígnea',
    side: 'ATK',
    speed: 3,
    roles: ['entry', 'soft-breach'],
    stats: { aim: 88, utility: 70, entry: 90, clutch: 78 },
    gadget: {
      name: 'Munição de Ruptura',
      tags: ['soft-breach'],
      counters: [],
      power: 0.65,
    },
    rarity: 'elite',
    draftWeight: 1,
  },
  {
    id: 'atk_gen_5',
    name: 'Malho',
    unit: 'Guarda Real',
    side: 'ATK',
    speed: 2,
    roles: ['soft-breach', 'entry'],
    stats: { aim: 84, utility: 74, entry: 82, clutch: 76 },
    gadget: {
      name: 'Marreta Pesada',
      tags: ['soft-breach'],
      counters: [],
      power: 0.6,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'atk_gen_6',
    name: 'Vespa',
    unit: 'Companhia Cinza',
    side: 'ATK',
    speed: 2,
    roles: ['intel', 'anti-gadget'],
    stats: { aim: 79, utility: 86, entry: 72, clutch: 74 },
    gadget: {
      name: 'Drone Elétrico',
      tags: ['intel', 'anti-gadget'],
      counters: ['trap', 'intel'],
      power: 0.72,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'atk_gen_7',
    name: 'Sabujo',
    unit: 'Patrulha Sul',
    side: 'ATK',
    speed: 2,
    roles: ['intel'],
    stats: { aim: 81, utility: 84, entry: 74, clutch: 78 },
    gadget: {
      name: 'Rastro Térmico',
      tags: ['intel'],
      counters: ['roam'],
      power: 0.78,
    },
    rarity: 'rare',
    draftWeight: 0.95,
  },
  {
    id: 'atk_gen_8',
    name: 'Clarão',
    unit: 'Divisão Aurora',
    side: 'ATK',
    speed: 2,
    roles: ['flash', 'entry'],
    stats: { aim: 80, utility: 82, entry: 80, clutch: 72 },
    gadget: {
      name: 'Fachos Cegantes',
      tags: ['flash'],
      counters: ['anchor'],
      power: 0.75,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'atk_gen_9',
    name: 'Muralha',
    unit: 'Guarda Real',
    side: 'ATK',
    speed: 2,
    roles: ['shield', 'flash', 'entry'],
    stats: { aim: 74, utility: 78, entry: 84, clutch: 80 },
    gadget: {
      name: 'Escudo de Choque',
      tags: ['shield', 'flash'],
      counters: ['anchor'],
      power: 0.68,
    },
    rarity: 'common',
    draftWeight: 1.05,
  },
  {
    id: 'atk_gen_10',
    name: 'Serra',
    unit: 'Patrulha Sul',
    side: 'ATK',
    speed: 2,
    roles: ['soft-breach', 'support'],
    stats: { aim: 83, utility: 76, entry: 78, clutch: 76 },
    gadget: {
      name: 'Chave Mestra',
      tags: ['soft-breach'],
      counters: [],
      power: 0.7,
    },
    rarity: 'common',
    draftWeight: 1.05,
  },
  {
    id: 'atk_gen_11',
    name: 'Estrondo',
    unit: 'Companhia Cinza',
    side: 'ATK',
    speed: 1,
    roles: ['support', 'soft-breach'],
    stats: { aim: 72, utility: 80, entry: 68, clutch: 70 },
    gadget: {
      name: 'Carga Fragmentada',
      tags: ['support'],
      counters: ['anchor'],
      power: 0.66,
    },
    rarity: 'common',
    draftWeight: 1.1,
  },
];

export const genericDefenseOperators: Operator[] = [
  {
    id: 'def_gen_0',
    name: 'Corrente',
    unit: 'Divisão Aurora',
    side: 'DEF',
    speed: 3,
    roles: ['anti-breach', 'roam'],
    stats: { aim: 84, utility: 84, entry: 76, clutch: 82 },
    gadget: {
      name: 'Fiação Viva',
      tags: ['anti-breach'],
      counters: ['hard-breach'],
      power: 0.82,
    },
    rarity: 'elite',
    draftWeight: 0.95,
  },
  {
    id: 'def_gen_1',
    name: 'Garra',
    unit: 'Vanguarda Norte',
    side: 'DEF',
    speed: 1,
    roles: ['anti-breach', 'anchor'],
    stats: { aim: 79, utility: 86, entry: 66, clutch: 80 },
    gadget: {
      name: 'Garra Elétrica',
      tags: ['anti-breach'],
      counters: ['hard-breach'],
      power: 0.85,
    },
    rarity: 'elite',
    draftWeight: 0.95,
  },
  {
    id: 'def_gen_2',
    name: 'Silêncio',
    unit: 'Guarda Real',
    side: 'DEF',
    speed: 2,
    roles: ['intel-denial', 'anti-breach', 'anchor'],
    stats: { aim: 76, utility: 88, entry: 64, clutch: 74 },
    gadget: {
      name: 'Bloqueador de Sinal',
      tags: ['intel-denial', 'anti-breach'],
      counters: ['intel', 'hard-breach'],
      power: 0.8,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'def_gen_3',
    name: 'Bruma',
    unit: 'Patrulha Leste',
    side: 'DEF',
    speed: 3,
    roles: ['intel-denial', 'roam'],
    stats: { aim: 83, utility: 78, entry: 78, clutch: 84 },
    gadget: {
      name: 'Manto de Ruído',
      tags: ['intel-denial'],
      counters: ['intel'],
      power: 0.74,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'def_gen_4',
    name: 'Presilha',
    unit: 'Companhia Cinza',
    side: 'DEF',
    speed: 2,
    roles: ['trap', 'anchor'],
    stats: { aim: 80, utility: 80, entry: 70, clutch: 78 },
    gadget: {
      name: 'Laço de Entrada',
      tags: ['trap'],
      counters: ['entry'],
      power: 0.55,
    },
    rarity: 'common',
    draftWeight: 1.05,
  },
  {
    id: 'def_gen_5',
    name: 'Geada',
    unit: 'Patrulha Sul',
    side: 'DEF',
    speed: 2,
    roles: ['trap', 'anchor'],
    stats: { aim: 78, utility: 82, entry: 68, clutch: 80 },
    gadget: {
      name: 'Cepo Congelante',
      tags: ['trap'],
      counters: ['entry'],
      power: 0.7,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'def_gen_6',
    name: 'Praga',
    unit: 'Patrulha Leste',
    side: 'DEF',
    speed: 2,
    roles: ['trap', 'intel'],
    stats: { aim: 81, utility: 84, entry: 72, clutch: 80 },
    gadget: {
      name: 'Espinhos Tóxicos',
      tags: ['trap', 'intel'],
      counters: ['entry'],
      power: 0.12,
    },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'def_gen_7',
    name: 'Vigília',
    unit: 'Esquadrão Maré',
    side: 'DEF',
    speed: 2,
    roles: ['intel', 'roam'],
    stats: { aim: 84, utility: 84, entry: 76, clutch: 86 },
    gadget: {
      name: 'Câmera Oculta',
      tags: ['intel'],
      counters: [],
      power: 0.8,
    },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'def_gen_8',
    name: 'Torreão',
    unit: 'Guarda Sul',
    side: 'DEF',
    speed: 1,
    roles: ['intel', 'anchor'],
    stats: { aim: 79, utility: 86, entry: 64, clutch: 82 },
    gadget: {
      name: 'Torre Blindada',
      tags: ['intel'],
      counters: [],
      power: 0.78,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'def_gen_9',
    name: 'Ferrolho',
    unit: 'Divisão Aurora',
    side: 'DEF',
    speed: 3,
    roles: ['anti-gadget', 'roam'],
    stats: { aim: 87, utility: 76, entry: 80, clutch: 84 },
    gadget: {
      name: 'Interceptador',
      tags: ['anti-gadget'],
      counters: ['flash'],
      power: 0.76,
    },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'def_gen_10',
    name: 'Enfermeiro',
    unit: 'Vanguarda Norte',
    side: 'DEF',
    speed: 1,
    roles: ['heal', 'anchor'],
    stats: { aim: 78, utility: 82, entry: 62, clutch: 80 },
    gadget: {
      name: 'Injetor de Campo',
      tags: ['heal'],
      counters: [],
      power: 0.8,
    },
    rarity: 'rare',
    draftWeight: 1,
  },
  {
    id: 'def_gen_11',
    name: 'Bastião',
    unit: 'Vanguarda Norte',
    side: 'DEF',
    speed: 1,
    roles: ['anchor', 'heal'],
    stats: { aim: 77, utility: 80, entry: 62, clutch: 78 },
    gadget: {
      name: 'Placas de Reforço',
      tags: ['heal'],
      counters: [],
      power: 0.7,
    },
    rarity: 'common',
    draftWeight: 1.1,
  },
];

export const genericOperators: Operator[] = [
  ...genericAttackOperators,
  ...genericDefenseOperators,
];

/**
 * Interchangeable with `operators.licensed.ts` — the build picks one via the
 * `@operators` alias, so the unselected pack never enters the bundle.
 */
export const operators = genericOperators;

