import type { Operator } from '@engine/types';

/**
 * ATTACK operators.
 *
 * NOTE ON IP: operator names, units and gadget names are Ubisoft trademarks and
 * live ONLY in this layer. The engine never references an operator id literal —
 * `purity.test.ts` enforces that — so swapping this file for
 * `operators.generic.ts` reskins the whole game without touching logic.
 */
export const attackOperators: Operator[] = [
  {
    id: 'atk_thermite',
    name: 'Thermite',
    unit: 'FBI SWAT',
    side: 'ATK',
    speed: 2,
    roles: ['hard-breach', 'support'],
    stats: { aim: 78, utility: 88, entry: 70, clutch: 72 },
    gadget: { name: 'Carga Exotérmica', tags: ['hard-breach'], counters: ['anti-breach'], power: 0.8 },
    rarity: 'elite',
    draftWeight: 1.0,
  },
  {
    id: 'atk_hibana',
    name: 'Hibana',
    unit: 'SAT',
    side: 'ATK',
    speed: 3,
    roles: ['hard-breach', 'entry'],
    stats: { aim: 82, utility: 84, entry: 78, clutch: 74 },
    gadget: { name: 'X-KAIROS', tags: ['hard-breach'], counters: ['anti-breach'], power: 0.75 },
    rarity: 'elite',
    draftWeight: 1.0,
  },
  {
    id: 'atk_thatcher',
    name: 'Thatcher',
    unit: 'SAS',
    side: 'ATK',
    speed: 2,
    roles: ['anti-gadget', 'support'],
    stats: { aim: 76, utility: 90, entry: 66, clutch: 70 },
    gadget: { name: 'Granada EMP', tags: ['anti-gadget'], counters: ['anti-breach', 'trap'], power: 0.85 },
    rarity: 'elite',
    draftWeight: 0.9,
  },
  {
    id: 'atk_iq',
    name: 'IQ',
    unit: 'GSG 9',
    side: 'ATK',
    speed: 3,
    roles: ['anti-gadget', 'intel'],
    stats: { aim: 80, utility: 82, entry: 74, clutch: 76 },
    gadget: { name: 'Detector Eletrônico', tags: ['anti-gadget', 'intel'], counters: ['trap'], power: 0.7 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'atk_ash',
    name: 'Ash',
    unit: 'FBI SWAT',
    side: 'ATK',
    speed: 3,
    roles: ['entry', 'soft-breach'],
    stats: { aim: 88, utility: 70, entry: 90, clutch: 78 },
    gadget: { name: 'Breaching Round', tags: ['soft-breach'], counters: [], power: 0.65 },
    rarity: 'elite',
    draftWeight: 1.0,
  },
  {
    id: 'atk_sledge',
    name: 'Sledge',
    unit: 'SAS',
    side: 'ATK',
    speed: 2,
    roles: ['soft-breach', 'entry'],
    stats: { aim: 84, utility: 74, entry: 82, clutch: 76 },
    gadget: { name: 'Marreta Tática', tags: ['soft-breach'], counters: [], power: 0.6 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'atk_twitch',
    name: 'Twitch',
    unit: 'GIGN',
    side: 'ATK',
    speed: 2,
    roles: ['intel', 'anti-gadget'],
    stats: { aim: 79, utility: 86, entry: 72, clutch: 74 },
    gadget: { name: 'Drone de Choque', tags: ['intel', 'anti-gadget'], counters: ['trap', 'intel'], power: 0.72 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'atk_jackal',
    name: 'Jackal',
    unit: 'GEO',
    side: 'ATK',
    speed: 2,
    roles: ['intel'],
    stats: { aim: 81, utility: 84, entry: 74, clutch: 78 },
    gadget: { name: 'Olhos de Caçador', tags: ['intel'], counters: ['roam'], power: 0.78 },
    rarity: 'rare',
    draftWeight: 0.95,
  },
  {
    id: 'atk_ying',
    name: 'Ying',
    unit: 'SDU',
    side: 'ATK',
    speed: 2,
    roles: ['flash', 'entry'],
    stats: { aim: 80, utility: 82, entry: 80, clutch: 72 },
    gadget: { name: 'Candela', tags: ['flash'], counters: ['anchor'], power: 0.75 },
    rarity: 'rare',
    draftWeight: 1.0,
  },
  {
    id: 'atk_blitz',
    name: 'Blitz',
    unit: 'GSG 9',
    side: 'ATK',
    speed: 2,
    roles: ['shield', 'flash', 'entry'],
    stats: { aim: 74, utility: 78, entry: 84, clutch: 80 },
    gadget: { name: 'Escudo Trilhante', tags: ['shield', 'flash'], counters: ['anchor'], power: 0.68 },
    rarity: 'common',
    draftWeight: 1.05,
  },
  {
    id: 'atk_buck',
    name: 'Buck',
    unit: 'JTF2',
    side: 'ATK',
    speed: 2,
    roles: ['soft-breach', 'support'],
    stats: { aim: 83, utility: 76, entry: 78, clutch: 76 },
    gadget: { name: 'Skeleton Key', tags: ['soft-breach'], counters: [], power: 0.7 },
    rarity: 'common',
    draftWeight: 1.05,
  },
  {
    id: 'atk_fuze',
    name: 'Fuze',
    unit: 'Spetsnaz',
    side: 'ATK',
    speed: 1,
    roles: ['support', 'soft-breach'],
    stats: { aim: 72, utility: 80, entry: 68, clutch: 70 },
    gadget: { name: 'Carga de Cluster', tags: ['support'], counters: ['anchor'], power: 0.66 },
    rarity: 'common',
    draftWeight: 1.1,
  },
];
